### PR TITLE
[WIP] Move to stylelint-codeguide

### LINKED ISSUE #232: Allow usage of stylelint 16.0
Hi,

this is just a GitHub reference that can be referenced by the commit messages that will allow stylelint 16

Blocked upstream by elirasza/stylelint-stylistic#17

WIP PR here: tagliala/stylelint-config-twbs-bootstrap#1, blocked by https://github.com/tagliala/stylelint-config-twbs-bootstrap/pull/1#issuecomment-1856018383

### PR DESCRIPTION
**Pull request by tagliala**
Move to stylelint-codeguide to allow the usage of stylelint 16

Ref: elirasza/stylelint-stylistic#17

Close #232

### CODE REVIEW

**Comment by firefoxic** [comment]
Hi! I'd advise you to take your time. I've got the renaming and organization move almost ready. Both github and npm addresses will change soon.

**Comment by tagliala** [comment]
Thanks for the heads-up!

Moved this PR draft, will keep an eye on the repo

**Comment by firefoxic** [comment]
It was in the plan to publish the package today. But for reasons beyond my control, I had to postpone publication until Wednesday.

But already now you can start preparing for the new package, if you follow the information from [this branch](https://github.com/stylelint-stylistic/stylelint-stylistic/tree/moving).

**Comment by tagliala** [comment]
Thanks. Everything is ready on my side I guess, waiting for the release

**Comment by tagliala** [comment]
Superseded by twbs/stylelint-config-twbs-bootstrap#236

**Pull request closed without merging**
